version: '3.8'
services:
  rstudio:
    build: .
    container_name: rstudio-server
    ports:
      - "8787:8787"
    environment:
      - PASSWORD=rstudio  # Set a secure password here
      - ROOT=TRUE              # Allows the user to access RStudio as root
    volumes:
      - ./rstudio-data:/home/rstudio  # Maps RStudio user directory to a named volume

volumes:
  rstudio-data:
